<?php

/**
 * @file
 * Creates the forms required for the bamp module.
 */

include 'bamp.helper.inc';
include 'bamp.input.inc';
include 'bamp.upload.inc';
include 'bamp.output.inc';
include 'bamp.search.inc';
include 'bamp.chart.inc';

function bamp_views_api() {
  return array(
    'api' => 2.0
  );
}

/**
 * Build the links in the navigation menu for each of the forms
 */
function bamp_menu() {

  $items['bamp'] = array(
    'title' => 'BAMP',
    'page callback' => 'bampmain_menu_callback',
    "access callback" => TRUE,
  );

  $items['bamp/Input forms'] = array(
    'title' => 'Input Forms',
    'page callback' => 'bampinput_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Input forms/Sample'] = array(
    'title' => 'Sample Form',
    'page callback' => 'bampsample_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Input forms/Farm'] = array(
    'title' => 'Farm Form',
    'page callback' => 'bampfarm_menu_callback',
    'access callback' => TRUE,
    );

  $items['bamp/Input forms/Site'] = array(
    'title' => 'Site Form',
    'page callback' => 'bampsite_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Input forms/Method'] = array(
    'title' => 'Method Form',
    'page callback' => 'bampmethod_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Input forms/Trip'] = array(
    'title' => 'Trip Form',
    'page callback' => 'bamptrip_menu_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['bamp/Input forms/Lab'] = array(
    'title' => 'Lab Form',
    'page callback' => 'bamplab_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Input forms/Results'] = array(
    'title' => 'Results Form',
    'page callback' => 'bampres_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Upload forms'] = array(
    'title' => 'Upload Forms',
    'page callback' => 'bampupload_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Upload forms/CSV upload'] = array(
    'title' => 'CSV upload',
    'page callback' => 'bampupcsv_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Upload forms/Crawford field results CSV upload'] = array(
    'title' => 'Crawford field results CSV upload',
    'page callback' => 'bampupcrawfield_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Upload forms/Crawford Site CSV upload'] = array(
    'title' => 'Crawford Site CSV upload',
    'page callback' => 'bampupcrawsite_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Upload forms/Crawford Lab results CSV upload'] = array(
    'title' => 'Crawford lab results CSV upload',
    'page callback' => 'bampupcrawlabr_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Report forms'] = array(
    'title' => 'Report Forms',
    'page callback' => 'bampreport_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Report forms/Farm'] = array(
    'title' => 'Farm report',
    'page callback' => 'bamprepfarm_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Report forms/Results'] = array(
    'title' => 'Combined results report',
    'page callback' => 'bamprepres_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Report forms/Field results'] = array(
    'title' => 'Field results report',
    'page callback' => 'bamprepfield_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Report forms/Lab results'] = array(
    'title' => 'Lab results report',
    'page callback' => 'bampreplab_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Report forms/Sites'] = array(
    'title' => 'Sites report',
    'page callback' => 'bamprepsite_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Search forms'] = array(
    'title' => 'Search Forms',
    'page callback' => 'bamp_search_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Search forms/Results'] = array(
    'title' => 'Search Results',
    'page callback' => 'bamp_search_results_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Charts'] = array(
    'title' => 'Charts',
    'page callback' => 'bamp_charts_menu_callback',
    'access callback' => TRUE,
  );

  $items['bamp/Charts/Chart1'] = array(
    'title' => 'Chart1',
    'page callback' => 'bamp_charts1_menu_callback',
    'access callback' => TRUE,
  );
  
  $items['bamp/Charts/Chart2'] = array(
    'title' => 'Chart2',
    'page callback' => 'bamp_charts2_menu_callback',
    'access callback' => TRUE,
  );
  
  return $items;
}

/**
 *  Create the main BAMP menu
 */
function bampmain_menu_callback() {
  drupal_set_title(t('BAMP Menu'));

  $content['form'] = array(
    '#markup' => '<p> This is the BAMP main menu</p>',
  );

  return $content;
}


