<?php

// $Id: bamp.module $

/**
 * @file
 * Creates the forms required for the bamp module.
 */

include 'bamp.helper.inc';
include 'bamp.input.inc';
include 'bamp.upload.inc';
include 'bamp.output.inc';
include 'bamp.search.inc';
include 'bamp.chart.inc';
include 'bamp.map.inc';
include 'bamp.edit.inc';
include 'bamp.changelog.inc';

function bamp_views_api() {
  return array(
    'api' => 2.0
  );
}

/**
 * Build the links in the navigation menu for each of the forms
 */
function bamp_menu() {

//  Main form
  $items['bamp'] = array(
    'title' => 'BAMP',
    'page callback' => 'bamp_main_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('bamp module'),
    'weight' => '0',
  );

//  Individual input forms
  $items['bamp/Input'] = array(
    'title' => 'Input Forms',
    'page callback' => 'bamp_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'weight' => '1',
  );

  $items['bamp/Input/Farm'] = array(
    'title' => 'Farm Form',
    'page callback' => 'bamp_farm_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    );

  $items['bamp/Input/Site'] = array(
    'title' => 'Site Form',
    'page callback' => 'bamp_site_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );

  $items['bamp/Input/Trip'] = array(
    'title' => 'Trip Form',
    'page callback' => 'bamp_trip_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
    'expanded' => TRUE,
  );

  $items['bamp/Input/Lab'] = array(
    'title' => 'Lab Form',
    'page callback' => 'bamp_lab_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );

  $items['bamp/Input/Field'] = array(
    'title' => 'Field results Form',
    'page callback' => 'bamp_field_input_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('input form'),
  );

//  Batch upload forms
  $items['bamp/Upload'] = array(
    'title' => 'Upload Forms',
    'page callback' => 'bamp_upload_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
    'weight' => '2',
  );

  $items['bamp/Upload/CrawfordField'] = array(
    'title' => 'Crawford field results CSV upload',
    'page callback' => 'bamp_upload_crawford_field_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );

  $items['bamp/Upload/CrawfordSite'] = array(
    'title' => 'Crawford Site CSV upload',
    'page callback' => 'bamp_upload_crawford_site_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );

  $items['bamp/Upload/CrawfordLab'] = array(
    'title' => 'Crawford lab results CSV upload',
    'page callback' => 'bamp_upload_crawford_lab_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
  $items['bamp/Upload/MartyField'] = array(
    'title' => 'Marty field results CSV upload',
    'page callback' => 'bamp_upload_marty_field_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
  $items['bamp/Upload/MartySite'] = array(
    'title' => 'Marty site results CSV upload',
    'page callback' => 'bamp_upload_marty_site_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
  $items['bamp/Upload/Marineharvest'] = array(
    'title' => 'Marineharvest results CSV upload',
    'page callback' => 'bamp_upload_marineharvest_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );

  $items['bamp/Upload/Weather'] = array(
    'title' => 'Weather CSV upload',
    'page callback' => 'bamp_upload_weather_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
  $items['bamp/Upload/Environment'] = array(
    'title' => 'Environment CSV upload',
    'page callback' => 'bamp_upload_environment_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
//  $items['bamp/Upload/DFOField'] = array(
//    'title' => 'DFO Field CSV upload',
//    'page callback' => 'dfo_upload_field_menu_callback',
//    'access callback' => 'user_access',
//    'access arguments' => array('upload form'),
//  );
  
  $items['bamp/Upload/DFOLab'] = array(
    'title' => 'DFO Lab CSV upload',
    'page callback' => 'dfo_upload_lab_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
  $items['bamp/Upload/DFOSite'] = array(
    'title' => 'DFO Site CSV upload',
    'page callback' => 'dfo_upload_site_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('upload form'),
  );
  
//  $items['bamp/Upload/DFOTrip'] = array(
//    'title' => 'DFO Trip CSV upload',
//    'page callback' => 'dfo_upload_trip_menu_callback',
//    'access callback' => 'user_access',
//    'access arguments' => array('upload form'),
//  );
 
//  Report generation forms
  $items['bamp/Report'] = array(
    'title' => 'Report Forms',
    'page callback' => 'bamp_report_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
    'weight' => '4',
  );
  
  $items['bamp/Report/Results'] = array(
    'title' => 'Combined results report',
    'page callback' => 'bamp_report_results_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );

  $items['bamp/Report/Field'] = array(
    'title' => 'Field results report',
    'page callback' => 'bamp_report_field_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Report/Lab'] = array(
    'title' => 'Lab results report',
    'page callback' => 'bamp_report_lab_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Report/Sites'] = array(
    'title' => 'Sites report',
    'page callback' => 'bamp_report_site_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Report/Environment'] = array(
    'title' => 'Environmental report',
    'page callback' => 'bamp_report_environment_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Report/Weather'] = array(
    'title' => 'Weather report',
    'page callback' => 'bamp_report_weather_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Report/Trip'] = array(
    'title' => 'Trip report',
    'page callback' => 'bamp_report_trip_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );

//  Entry edit forms
  $items['bamp/Edit'] = array(
    'title' => 'Edit Forms',
    'page callback' => 'bamp_edit_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
    'weight' => '5',
  );
  
  $items['bamp/Edit/Field'] = array(
    'title' => 'Field edit form',
    'page callback' => 'bamp_edit_field_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
  
  $items['bamp/Edit/Lab'] = array(
    'title' => 'Lab edit form',
    'page callback' => 'bamp_edit_lab_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
  
  $items['bamp/Edit/Site'] = array(
    'title' => 'Site edit form',
    'page callback' => 'bamp_edit_site_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
  
  $items['bamp/Edit/Trip'] = array(
    'title' => 'Trip edit form',
    'page callback' => 'bamp_edit_trip_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
  
  $items['bamp/Edit/Weather'] = array(
    'title' => 'Weather edit form',
    'page callback' => 'bamp_edit_weather_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
  
  $items['bamp/Edit/Environment'] = array(
    'title' => 'Environment edit form',
    'page callback' => 'bamp_edit_environment_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('edit form'),
  );
 
//  Data search forms
  $items['bamp/Search'] = array(
    'title' => 'Search Forms',
    'page callback' => 'bamp_search_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
    'weight' => '3',
  );

  $items['bamp/Search/Results'] = array(
    'title' => 'Search Field Results',
    'page callback' => 'bamp_search_results_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
 
//  Data charting forms
  $items['bamp/Charts'] = array(
    'title' => 'Charts',
    'page callback' => 'bamp_charts_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
    'weight' => '6',
  );

  $items['bamp/Charts/Chart1'] = array(
    'title' => 'Chart1',
    'page callback' => 'bamp_charts1_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
  $items['bamp/Charts/Chart2'] = array(
    'title' => 'Chart2',
    'page callback' => 'bamp_charts2_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );

//  Map generation forms
  $items['bamp/Maps'] = array(
    'title' => 'Maps',
    'page callback' => 'bamp_maps_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
    'weight' => '7',
  );

  $items['bamp/Maps/Maps1'] = array(
    'title' => 'Maps1',
    'page callback' => 'bamp_maps1_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('report form'),
  );
  
//  Changelog forms
  $items['bamp/Changelog'] = array(
    'title' => 'Change log',
    'page callback' => 'bamp_changelog_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('changelog form'),
    'weight' => '8',
  );
  
  $items['bamp/Changelog/Results'] = array(
    'title' => 'Change log results',
    'page callback' => 'bamp_changelog_results_menu_callback',
    'access callback' => 'user_access',
    'access arguments' => array('changelog form'),
  );
  
  return $items;
}

/**
 *  Create the main BAMP menu
 */
function bamp_main_menu_callback() {
  drupal_set_title(t('BAMP Menu'));

  $content['form'] = array(
    '#markup' => '<p> This is the BAMP main menu</p>',
  );

  return $content;
}

function bamp_permission() {
  return array(
    'bamp module' => array(
      'title' => t('BAMP module access'),
      'description' => t('Access to the BAMP module'),
    ),
    'input form' => array(
      'title' => t('BAMP input form access'),
      'description' => t('Access to the BAMP input formsd'),
    ),
    'upload form' => array(
      'title' => t('BAMP upload form access'),
      'description' => t('Access to the BAMP upload forms'),
    ),
    'report form' => array(
      'title' => t('BAMP report form access'),
      'description' => t('Access to the BAMP report forms'),
    ),
    'edit form' => array(
      'title' => t('BAMP edit form access'),
      'description' => t('Access to the BAMP edit forms'),
    ),
    'changelog form' => array(
      'title' => t('BAMP change log form access'),
      'description' => t('Access to the BAMP change log forms'),
    ),
  );
}
